version: "3.9"
networks:
  roboshop:
    driver: bridge
services:                   #containers we are going to run , we write under services
  web:                      #name of container
    image: kalyanreddy932/roboshop:web-user-catalogue-mongodb
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
  mongodb:
    image: kalyanreddy932/robotshop:mongodb
    container_name: mongodb
  catalogue:
    image: kalyanreddy932/robotshop:catalogue
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis
    container_name: redis
  user:
    image: kalyanreddy932/robotshop:user
    container_name: user
    depends_on:
    - mongodb
    - redis