version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: kalyanreddy932/roboshop:web-user-catalogue-mongodb-compose1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: kalyanreddy932/robotshop:mongodb-compose1
    container_name: mongodb
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: kalyanreddy932/robotshop:catalogue-compose1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis
    container_name: redis
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: kalyanreddy932/robotshop:user-compose1
    container_name: user
    depends_on:
    - mongodb
    - redis