version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: kalyanreddy932/roboshop:web-shipping-cart-user-catalogue-mongodb-compose2
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
    - shipping
  mongodb:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: kalyanreddy932/robotshop:mongodb-compose1
    container_name: mongodb
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: kalyanreddy932/robotshop:catalogue-compose1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis
    container_name: redis
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: kalyanreddy932/robotshop:user-compose1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    image: kalyanreddy932/roboshop:cart-compose1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql:v1
    container_name: kalyanreddy932/roboshop:mysql-compose1
  shipping:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    image: kalyanreddy932/roboshop:shipping-compose1
    container_name: shipping
    depends_on:
    - mysql